interface ZIF_CDS_MONSTER_DELIVERIES_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZCDS_MONSTER_DELIVERIES,
 ACTIVATION                     TYPE /BOBF/ACT_KEY VALUE '005056B074C91ED8A0A42C279C97810F',
 CREATE_ZCDS_MONSTER_DELIVERIES TYPE /BOBF/ACT_KEY VALUE '005056B074C91ED8A0A42C279C94C10F',
 DELETE_ZCDS_MONSTER_DELIVERIES TYPE /BOBF/ACT_KEY VALUE '005056B074C91ED8A0A42C279C95410F',
 EDIT                           TYPE /BOBF/ACT_KEY VALUE '005056B074C91ED8A0A42C279C97610F',
 LOCK_ZCDS_MONSTER_DELIVERIES   TYPE /BOBF/ACT_KEY VALUE '005056B074C91ED8A0A42C279C94010F',
 PREPARATION                    TYPE /BOBF/ACT_KEY VALUE '005056B074C91ED8A0A42C279C97C10F',
 SAVE_ZCDS_MONSTER_DELIVERIES   TYPE /BOBF/ACT_KEY VALUE '005056B074C91ED8A0A42C279C95C10F',
 UNLOCK_ZCDS_MONSTER_DELIVERIES TYPE /BOBF/ACT_KEY VALUE '005056B074C91ED8A0A42C279C94410F',
 UPDATE_ZCDS_MONSTER_DELIVERIES TYPE /BOBF/ACT_KEY VALUE '005056B074C91ED8A0A42C279C95010F',
 VALIDATE_ZCDS_MONSTER_DELIVERI TYPE /BOBF/ACT_KEY VALUE '005056B074C91ED8A0A42C279C95810F',
 VALIDATION                     TYPE /BOBF/ACT_KEY VALUE '005056B074C91ED8A0A42C279C97A10F',
      END OF ZCDS_MONSTER_DELIVERIES,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZCDS_MONSTER_DELIVERIES,
        BEGIN OF EDIT,
 PRESERVE_CHANGES               TYPE STRING VALUE 'PRESERVE_CHANGES',
        END OF EDIT,
        BEGIN OF LOCK_ZCDS_MONSTER_DELIVERIES,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZCDS_MONSTER_DELIVERIES,
        BEGIN OF PREPARATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF PREPARATION,
        BEGIN OF UNLOCK_ZCDS_MONSTER_DELIVERIES,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZCDS_MONSTER_DELIVERIES,
        BEGIN OF VALIDATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF VALIDATION,
      END OF ZCDS_MONSTER_DELIVERIES,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZCDS_MONSTER_DELIVERIES,
 ACTIVE_ENTITY_KEY              TYPE /BOBF/OBM_ALTKEY_KEY VALUE '005056B074C91ED8A0A42C279C97410F',
      END OF ZCDS_MONSTER_DELIVERIES,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZCDS_MONSTER_DELIVERIES,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91ED8A0A42C279C93E10F',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91ED8A0A42C279C93A10F',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91ED8A0A42C279C94A10F',
      END OF ZCDS_MONSTER_DELIVERIES,
      BEGIN OF ZCDS_MONSTER_DELIVERIES_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91ED8A0A42C279C96210F',
      END OF ZCDS_MONSTER_DELIVERIES_LOCK,
      BEGIN OF ZCDS_MONSTER_DELIVERIES_MESSAG,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91ED8A0A42C279C96010F',
      END OF ZCDS_MONSTER_DELIVERIES_MESSAG,
      BEGIN OF ZCDS_MONSTER_DELIVERIES_PROPER,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91ED8A0A42C279C96410F',
      END OF ZCDS_MONSTER_DELIVERIES_PROPER,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZCDS_MONSTER_DELIVERIES,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZCDS_MONSTER_DELIVERIES,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '005056B074C91ED8A0A42C279C93010F' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZCDS_MONSTER_DELIVERIES' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZCDS_MONSTER_DELIVERIES,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '005056B074C91ED8A0A42C279C97E10F',
 CENTRAL_ADMIN_DATA             TYPE /BOBF/DET_KEY VALUE '005056B074C91ED8A0A42C279C98010F',
 DELETE_DRAFT_WHN_ACTIVE_DELETE TYPE /BOBF/DET_KEY VALUE '005056B074C91ED8A0A42C279C98E10F',
 DRAFT_ACTION_CONTROL           TYPE /BOBF/DET_KEY VALUE '005056B074C91ED8A0A42C279C98C10F',
 DRAFT_SYS_ADMIN_DATA           TYPE /BOBF/DET_KEY VALUE '005056B074C91ED8A0A42C279C98210F',
 DURABLE_LOCK_CLEANUP_CLEANUP   TYPE /BOBF/DET_KEY VALUE '005056B074C91ED8A0A42C279C98A10F',
 DURABLE_LOCK_CLEANUP_DELETE    TYPE /BOBF/DET_KEY VALUE '005056B074C91ED8A0A42C279C98410F',
 DURABLE_LOCK_CLEANUP_FAIL_SAVE TYPE /BOBF/DET_KEY VALUE '005056B074C91ED8A0A42C279C98810F',
 DURABLE_LOCK_CLEANUP_SUCC_SAVE TYPE /BOBF/DET_KEY VALUE '005056B074C91ED8A0A42C279C98610F',
      END OF ZCDS_MONSTER_DELIVERIES,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 DRAFT_CONSISTENCY              TYPE /BOBF/OBM_GROUP_KEY VALUE '005056B074C91ED8A0A42C279C96810F',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZCDS_MONSTER_DELIVERIES        TYPE /BOBF/OBM_NODE_KEY VALUE '005056B074C91ED8A0A42C279C93410F',
 ZCDS_MONSTER_DELIVERIES_LOCK   TYPE /BOBF/OBM_NODE_KEY VALUE '005056B074C91ED8A0A42C279C93C10F',
 ZCDS_MONSTER_DELIVERIES_MESSAG TYPE /BOBF/OBM_NODE_KEY VALUE '005056B074C91ED8A0A42C279C93810F',
 ZCDS_MONSTER_DELIVERIES_PROPER TYPE /BOBF/OBM_NODE_KEY VALUE '005056B074C91ED8A0A42C279C94810F',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZCDS_MONSTER_DELIVERIES,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  DELIVERY_NUMBER                TYPE STRING VALUE 'DELIVERY_NUMBER',
  ORDER_NUMBER                   TYPE STRING VALUE 'ORDER_NUMBER',
  ORDER_ITEM                     TYPE STRING VALUE 'ORDER_ITEM',
  MONSTER_NUMBER                 TYPE STRING VALUE 'MONSTER_NUMBER',
  MONSTER_NAME                   TYPE STRING VALUE 'MONSTER_NAME',
  CASTLE_NUMBER                  TYPE STRING VALUE 'CASTLE_NUMBER',
  VILLAGE_NUMBER                 TYPE STRING VALUE 'VILLAGE_NUMBER',
  VILLAGE_ADDRESS                TYPE STRING VALUE 'VILLAGE_ADDRESS',
  TASK_DESCRIPTION               TYPE STRING VALUE 'TASK_DESCRIPTION',
  DUE_DATE                       TYPE STRING VALUE 'DUE_DATE',
  DUE_TIME                       TYPE STRING VALUE 'DUE_TIME',
  ACTUAL_DATE                    TYPE STRING VALUE 'ACTUAL_DATE',
  ACTUAL_TIME                    TYPE STRING VALUE 'ACTUAL_TIME',
  NOP_MURDERED                   TYPE STRING VALUE 'NOP_MURDERED',
  CURRENT_STATUS                 TYPE STRING VALUE 'CURRENT_STATUS',
  ACTIVEUUID                     TYPE STRING VALUE 'ACTIVEUUID',
  HASACTIVEENTITY                TYPE STRING VALUE 'HASACTIVEENTITY',
  DRAFTENTITYCREATIONDATETIME    TYPE STRING VALUE 'DRAFTENTITYCREATIONDATETIME',
  DRAFTENTITYLASTCHANGEDATETIME  TYPE STRING VALUE 'DRAFTENTITYLASTCHANGEDATETIME',
  DRAFTENTITYCONSISTENCYSTATUS   TYPE STRING VALUE 'DRAFTENTITYCONSISTENCYSTATUS',
  ISACTIVEENTITY                 TYPE STRING VALUE 'ISACTIVEENTITY',
      END OF ZCDS_MONSTER_DELIVERIES,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZCDS_MONSTER_DELIVERIES,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '005056B074C91ED8A0A42C279C93610F',
      END OF ZCDS_MONSTER_DELIVERIES,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_STATUS_VARIABLE,
      BEGIN OF ZCDS_MONSTER_DELIVERIES,
 DRAFT_CONSISTENCY_STATUS       TYPE /BOBF/STA_VAR_KEY VALUE '005056B074C91ED8A0A42C279C96610F',
      END OF ZCDS_MONSTER_DELIVERIES,
    END OF SC_STATUS_VARIABLE .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZCDS_MONSTER_DELIVERIES,
 DURABLE_LOCK_CREATE_FOR_NEW    TYPE /BOBF/VAL_KEY VALUE '005056B074C91ED8A0A42C279C99010F',
      END OF ZCDS_MONSTER_DELIVERIES,
    END OF SC_VALIDATION .
endinterface.
