class ZCX_VIOLATED_PRECONDITION_STAT definition
  public
  inheriting from CX_STATIC_CHECK
  create public .

public section.

  constants ZCX_VIOLATED_PRECONDITION_STAT type SOTR_CONC value '005056B074C91ED981A35452159CC110' ##NO_TEXT.
  data MD_CONDITION type ITEX132 .
  data MO_ERROR_LOG type ref to ZCL_BC_MESSAGE_HANDLER .
  data MD_CALLING_PROGRAM type DBGLPROG .
  data MD_CALLING_ROUTINE type DBGLEVENT .

  methods CONSTRUCTOR
    importing
      !TEXTID like TEXTID optional
      !PREVIOUS like PREVIOUS optional
      !MD_CONDITION type ITEX132 optional
      !MO_ERROR_LOG type ref to ZCL_BC_MESSAGE_HANDLER optional
      !MD_CALLING_PROGRAM type DBGLPROG optional
      !MD_CALLING_ROUTINE type DBGLEVENT optional .
protected section.
private section.
ENDCLASS.



CLASS ZCX_VIOLATED_PRECONDITION_STAT IMPLEMENTATION.


  method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
TEXTID = TEXTID
PREVIOUS = PREVIOUS
.
 IF textid IS INITIAL.
   me->textid = ZCX_VIOLATED_PRECONDITION_STAT .
 ENDIF.
me->MD_CONDITION = MD_CONDITION .
me->MO_ERROR_LOG = MO_ERROR_LOG .
me->MD_CALLING_PROGRAM = MD_CALLING_PROGRAM .
me->MD_CALLING_ROUTINE = MD_CALLING_ROUTINE .
  endmethod.
ENDCLASS.
